name = "vivivanandkennethswedding"
type = 'webpack'
account_id = ''
routes = ['bryllup.wangpedersen.com/*', 'wedding.wangpedersen.com/*']
zone_id = ''
usage_model = ''
workers_dev = true
target_type = "webpack"
site = {bucket = "public",entry-point = "workers-site"}
